name: advance_booking_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5
  geolocator: ^11.1.0
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  geocoding: ^2.2.2
  http: ^1.2.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
